### ISSUE TITLE
Bug in tagmanager.js

### ISSUE THREAD

**Issue by qasim-feroz** [redvanworkshop/sfcc-plugin-gtm#10]
There is a spelling error at line np. 29 of the files `cartridge/static/default/js/tagmanager.js`. The variable is defined as `gmtData` and is referenced as `gtmData`. This cause the gtm `add-to-cart` listener to break every time a product is added to cart.

I tried to make the update myself but could not push the code because access was denied.

**Comment by asecaida** [comment]
Thanks @qasimferoze.  It has been addressed along with a few more things.
