### ISSUE TITLE
ReferenceError: "Logger" is not defined. (plugin_gtm/cartridge/scripts/gtm/gtmHelpers.js#258)

### ISSUE THREAD

**Issue by ShahzadHafeez** [redvanworkshop/sfcc-plugin-gtm#5]
Logger.error is used without first requiring the dw.system.Logger.

file path: sfcc-plugin-gtm\cartridges\plugin_gtm\cartridge\scripts\gtm\gtmHelpers.js
line No: 258
line code: Logger.error('GTMHelpers - cannot retrieve order');

Solution:
You need to require dw.system.Logger and then you can use its error method.

**Comment by asecaida** [comment]
Thanks.  I'll get that updated right away.

**Comment by asecaida** [comment]
Issue was updated, thanks again. https://github.com/redvanworkshop/sfcc-plugin-gtm/pull/6/files
